<?php
declare(strict_types=1);

namespace LabelPrint\Pdf;

use LabelPrint\Support\Log;

/**
 * Общая часть растеризаторов, читающих формат Netpbm из stdout внешней программы.
 *
 * Все страницы рендерятся ОДНИМ вызовом, результат приходит склеенным потоком.
 * Запуск процесса — самая дорогая часть конвейера (у Ghostscript это 43 мс из 57),
 * и платить её за каждую страницу нет смысла. Файлы Netpbm самоописываемы,
 * поэтому склеенный поток разбирается последовательно.
 */
abstract class PnmRasterizer implements RasterizerInterface
{
    public function __construct(
        protected readonly string $binary,
        protected readonly Log $log,
        protected readonly int $timeoutSeconds = 30,
        /** Предохранитель от «бомб»: максимум точек в растре одной страницы. */
        protected readonly int $maxDots = 40_000_000,
    ) {
    }

    /** @return list<string> */
    abstract protected function buildCommand(string $pdfPath, float $dpi): array;

    /** 'P5' — 8 бит серого с собственным порогом, 'P4' — готовый 1 бит. */
    abstract protected function magic(): string;

    public function isAvailable(): bool
    {
        return is_executable($this->binary);
    }

    /**
     * @return list<Bitmap>
     */
    public function rasterize(string $pdfPath, float $dpi, int $threshold = 128): array
    {
        if (!is_file($pdfPath) || !is_readable($pdfPath)) {
            throw new \RuntimeException("PDF недоступен для чтения: {$pdfPath}");
        }

        if ($dpi <= 0) {
            throw new \InvalidArgumentException("Разрешение должно быть положительным, задано {$dpi}");
        }

        $started = hrtime(true);
        [$stdout, $stderr, $exitCode] = $this->run($this->buildCommand($pdfPath, $dpi));
        $elapsedMs = (int) ((hrtime(true) - $started) / 1_000_000);

        if ($exitCode !== 0) {
            throw new \RuntimeException(
                sprintf('%s завершился с кодом %d: %s', $this->name(), $exitCode, $this->tail($stderr)),
            );
        }

        if ($stdout === '') {
            throw new \RuntimeException(
                sprintf('%s не выдал ни одной страницы. %s', $this->name(), $this->tail($stderr)),
            );
        }

        $pages = $this->splitPages($stdout, $threshold);

        $this->log->debug('страницы отрендерены', [
            'engine' => $this->name(),
            'pdf' => basename($pdfPath),
            'pages' => count($pages),
            'dpi' => round($dpi, 2),
            'ms' => $elapsedMs,
            'raster_bytes' => strlen($stdout),
        ]);

        return $pages;
    }

    /**
     * Разбирает склеенный поток Netpbm на отдельные растры.
     *
     * @return list<Bitmap>
     */
    protected function splitPages(string $stream, int $threshold): array
    {
        $magic = $this->magic();
        $gray = $magic === 'P5';
        $pages = [];
        $offset = 0;
        $len = strlen($stream);

        while ($offset < $len) {
            // Пропускаем возможные пустые строки между страницами.
            while ($offset < $len && ($stream[$offset] === "\n" || $stream[$offset] === "\r")) {
                $offset++;
            }
            if ($offset >= $len) {
                break;
            }

            if (substr($stream, $offset, 2) !== $magic) {
                throw new \RuntimeException(sprintf(
                    'Ожидался %s на позиции %d, получено "%s". Похоже, %s написал в stdout что-то ещё.',
                    $magic,
                    $offset,
                    substr($stream, $offset, 16),
                    $this->name(),
                ));
            }

            $chunk = substr($stream, $offset);
            $bitmap = $gray ? Bitmap::fromPgm($chunk, $threshold) : Bitmap::fromPbm($chunk);

            if ($bitmap->width * $bitmap->height > $this->maxDots) {
                throw new \RuntimeException(sprintf(
                    'Растр страницы слишком велик: %dx%d = %d точек при лимите %d',
                    $bitmap->width,
                    $bitmap->height,
                    $bitmap->width * $bitmap->height,
                    $this->maxDots,
                ));
            }

            $pages[] = $bitmap;
            $offset += $this->consumedBytes($chunk, $bitmap, $gray);
        }

        if ($pages === []) {
            throw new \RuntimeException('В выводе ' . $this->name() . ' не нашлось ни одной страницы');
        }

        return $pages;
    }

    /**
     * Сколько байт занимает одна картинка в потоке: заголовок плюс данные.
     *
     * Ghostscript вставляет в заголовок строку комментария
     * («# Image generated by GPL Ghostscript»), длина которой зависит от устройства,
     * поэтому смещение считается разбором, а не по фиксированной длине.
     */
    protected function consumedBytes(string $chunk, Bitmap $bitmap, bool $gray): int
    {
        $fields = $gray ? 3 : 2;
        $pos = 2;
        $len = strlen($chunk);

        for ($i = 0; $i < $fields; $i++) {
            while ($pos < $len) {
                $ch = $chunk[$pos];
                if ($ch === '#') {
                    while ($pos < $len && $chunk[$pos] !== "\n") {
                        $pos++;
                    }
                    continue;
                }
                if ($ch === ' ' || $ch === "\t" || $ch === "\n" || $ch === "\r") {
                    $pos++;
                    continue;
                }
                break;
            }
            while ($pos < $len && $chunk[$pos] >= '0' && $chunk[$pos] <= '9') {
                $pos++;
            }
        }
        $pos++;   // единственный разделитель перед данными

        $body = $gray
            ? $bitmap->width * $bitmap->height
            : $bitmap->bytesPerRow * $bitmap->height;

        return $pos + $body;
    }

    /**
     * Запускает процесс, читая stdout и stderr одновременно.
     *
     * Читать надо именно параллельно: буфер канала в Linux — 64 КБ, и если выбирать
     * только stdout, процесс намертво встанет на записи в переполненный stderr
     * (или наоборот). Растр этикетки — это сотни килобайт, так что порог достигается легко.
     *
     * @param  list<string> $command
     * @return array{0:string,1:string,2:int}
     */
    protected function run(array $command): array
    {
        $descriptors = [
            0 => ['file', '/dev/null', 'r'],
            1 => ['pipe', 'w'],
            2 => ['pipe', 'w'],
        ];

        $process = @proc_open($command, $descriptors, $pipes);
        if (!is_resource($process)) {
            throw new \RuntimeException("Не удалось запустить {$this->name()}: {$this->binary}");
        }

        stream_set_blocking($pipes[1], false);
        stream_set_blocking($pipes[2], false);

        $stdout = '';
        $stderr = '';
        $deadline = microtime(true) + $this->timeoutSeconds;
        $open = [1 => $pipes[1], 2 => $pipes[2]];

        while ($open !== []) {
            $read = array_values($open);
            $write = null;
            $except = null;

            $remaining = $deadline - microtime(true);
            if ($remaining <= 0) {
                $this->terminate($process, $pipes);
                throw new \RuntimeException(
                    "{$this->name()} не уложился в {$this->timeoutSeconds} с и был остановлен",
                );
            }

            $ready = @stream_select($read, $write, $except, (int) $remaining, 200_000);
            if ($ready === false) {
                break;
            }

            foreach ($read as $stream) {
                $chunk = fread($stream, 262_144);
                if ($chunk === false || $chunk === '') {
                    if (feof($stream)) {
                        foreach ($open as $key => $candidate) {
                            if ($candidate === $stream) {
                                fclose($stream);
                                unset($open[$key]);
                            }
                        }
                    }
                    continue;
                }

                if ($stream === $pipes[1]) {
                    $stdout .= $chunk;
                } else {
                    $stderr .= $chunk;
                }
            }
        }

        foreach ($open as $stream) {
            fclose($stream);
        }

        return [$stdout, $stderr, proc_close($process)];
    }

    /**
     * @param resource            $process
     * @param array<int,resource> $pipes
     */
    private function terminate($process, array $pipes): void
    {
        foreach ($pipes as $pipe) {
            if (is_resource($pipe)) {
                fclose($pipe);
            }
        }
        proc_terminate($process, SIGKILL);
        proc_close($process);
    }

    protected function tail(string $text, int $limit = 600): string
    {
        $text = trim($text);
        if ($text === '') {
            return '(stderr пуст)';
        }

        return strlen($text) > $limit ? '…' . substr($text, -$limit) : $text;
    }

    /** Дробное разрешение в виде строки: без запятой из локали и без экспоненты. */
    protected static function formatDpi(float $dpi): string
    {
        return rtrim(rtrim(number_format($dpi, 4, '.', ''), '0'), '.');
    }
}
