<?php
declare(strict_types=1);

namespace LabelPrint\Pdf;

use LabelPrint\Support\Log;
use LabelPrint\Support\Process;

/**
 * Общая часть растеризаторов, читающих формат Netpbm из stdout внешней программы.
 *
 * Все страницы рендерятся ОДНИМ вызовом, результат приходит склеенным потоком.
 * Запуск процесса — самая дорогая часть конвейера (у Ghostscript это 43 мс из 57),
 * и платить её за каждую страницу нет смысла. Файлы Netpbm самоописываемы,
 * поэтому склеенный поток разбирается последовательно.
 */
abstract class PnmRasterizer implements RasterizerInterface
{
    public function __construct(
        protected readonly string $binary,
        protected readonly Log $log,
        protected readonly int $timeoutSeconds = 30,
        /** Предохранитель от «бомб»: максимум точек в растре одной страницы. */
        protected readonly int $maxDots = 40_000_000,
    ) {
    }

    /** @return list<string> */
    abstract protected function buildCommand(string $pdfPath, float $dpi): array;

    /** 'P5' — 8 бит серого с собственным порогом, 'P4' — готовый 1 бит. */
    abstract protected function magic(): string;

    public function isAvailable(): bool
    {
        return is_executable($this->binary);
    }

    /**
     * @return list<Bitmap>
     */
    public function rasterize(string $pdfPath, float $dpi, int $threshold = 128): array
    {
        if (!is_file($pdfPath) || !is_readable($pdfPath)) {
            throw new \RuntimeException("PDF недоступен для чтения: {$pdfPath}");
        }

        if ($dpi <= 0) {
            throw new \InvalidArgumentException("Разрешение должно быть положительным, задано {$dpi}");
        }

        $started = hrtime(true);
        $result = Process::run($this->buildCommand($pdfPath, $dpi), $this->timeoutSeconds);
        [$stdout, $stderr, $exitCode] = [$result['stdout'], $result['stderr'], $result['code']];
        $elapsedMs = (int) ((hrtime(true) - $started) / 1_000_000);

        if ($exitCode !== 0) {
            throw new \RuntimeException(
                sprintf('%s завершился с кодом %d: %s', $this->name(), $exitCode, Process::tail($stderr)),
            );
        }

        if ($stdout === '') {
            throw new \RuntimeException(
                sprintf('%s не выдал ни одной страницы. %s', $this->name(), Process::tail($stderr)),
            );
        }

        $pages = $this->splitPages($stdout, $threshold);

        $this->log->debug('страницы отрендерены', [
            'engine' => $this->name(),
            'pdf' => basename($pdfPath),
            'pages' => count($pages),
            'dpi' => round($dpi, 2),
            'ms' => $elapsedMs,
            'raster_bytes' => strlen($stdout),
        ]);

        return $pages;
    }

    /**
     * Разбирает склеенный поток Netpbm на отдельные растры.
     *
     * @return list<Bitmap>
     */
    protected function splitPages(string $stream, int $threshold): array
    {
        $magic = $this->magic();
        $gray = $magic === 'P5';
        $pages = [];
        $offset = 0;
        $len = strlen($stream);

        while ($offset < $len) {
            // Пропускаем возможные пустые строки между страницами.
            while ($offset < $len && ($stream[$offset] === "\n" || $stream[$offset] === "\r")) {
                $offset++;
            }
            if ($offset >= $len) {
                break;
            }

            if (substr($stream, $offset, 2) !== $magic) {
                throw new \RuntimeException(sprintf(
                    'Ожидался %s на позиции %d, получено "%s". Похоже, %s написал в stdout что-то ещё.',
                    $magic,
                    $offset,
                    substr($stream, $offset, 16),
                    $this->name(),
                ));
            }

            $chunk = substr($stream, $offset);
            $bitmap = $gray ? Bitmap::fromPgm($chunk, $threshold) : Bitmap::fromPbm($chunk);

            if ($bitmap->width * $bitmap->height > $this->maxDots) {
                throw new \RuntimeException(sprintf(
                    'Растр страницы слишком велик: %dx%d = %d точек при лимите %d',
                    $bitmap->width,
                    $bitmap->height,
                    $bitmap->width * $bitmap->height,
                    $this->maxDots,
                ));
            }

            $pages[] = $bitmap;
            $offset += $this->consumedBytes($chunk, $bitmap, $gray);
        }

        if ($pages === []) {
            throw new \RuntimeException('В выводе ' . $this->name() . ' не нашлось ни одной страницы');
        }

        return $pages;
    }

    /**
     * Сколько байт занимает одна картинка в потоке: заголовок плюс данные.
     *
     * Ghostscript вставляет в заголовок строку комментария
     * («# Image generated by GPL Ghostscript»), длина которой зависит от устройства,
     * поэтому смещение считается разбором, а не по фиксированной длине.
     */
    protected function consumedBytes(string $chunk, Bitmap $bitmap, bool $gray): int
    {
        $fields = $gray ? 3 : 2;
        $pos = 2;
        $len = strlen($chunk);

        for ($i = 0; $i < $fields; $i++) {
            while ($pos < $len) {
                $ch = $chunk[$pos];
                if ($ch === '#') {
                    while ($pos < $len && $chunk[$pos] !== "\n") {
                        $pos++;
                    }
                    continue;
                }
                if ($ch === ' ' || $ch === "\t" || $ch === "\n" || $ch === "\r") {
                    $pos++;
                    continue;
                }
                break;
            }
            while ($pos < $len && $chunk[$pos] >= '0' && $chunk[$pos] <= '9') {
                $pos++;
            }
        }
        $pos++;   // единственный разделитель перед данными

        $body = $gray
            ? $bitmap->width * $bitmap->height
            : $bitmap->bytesPerRow * $bitmap->height;

        return $pos + $body;
    }

    /** Дробное разрешение в виде строки: без запятой из локали и без экспоненты. */
    protected static function formatDpi(float $dpi): string
    {
        return rtrim(rtrim(number_format($dpi, 4, '.', ''), '0'), '.');
    }
}
